db:
   username: postgres
   password: root
   url: www.tut.by

   properties:
      first: 1
      last: 2
      key: value

   pool:
      size: 10
      timeout: 20

   pools:
      - size: 10
        timeout: 20
      - size: 10
        timeout: 20
      - size: 10
        timeout: 20
logging:
  level:
     root: WARN
     com.vm.springstarter.pool: INFO
  file:
    name: com.vm
    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://flora.db.elephantsql.com:5432/bpjvmqeo
    username: bpjvmqeo
    password: Z7r9RiFcIXBGOkVkROUXpR8XhluwvjzU
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false

